const dummyData = [
    {
        "copyright": "Sebastian Voltmer",
        "date": "2017-01-01",
        "explanation": "Higher than the highest building, higher than the highest mountain, higher than the highest airplane, lies the realm of the aurora.  Auroras rarely reach below 60 kilometers, and can range up to 1000 kilometers.  Aurora light results from energetic electrons and protons striking molecules in the Earth's atmosphere.  Frequently, when viewed from space, a complete aurora will appear as a circle around one of the Earth's magnetic poles.  The featured wide-angle image, horizontally compressed, captured an unexpected auroral display that stretched across the sky five years ago over eastern Norway.",
        "hdurl": "https://apod.nasa.gov/apod/image/1701/aurora_voltmer_1920.jpg", "media_type": "image", "service_version": "v1", "title": "A Full Sky Aurora Over Norway", "url": "https://apod.nasa.gov/apod/image/1701/aurora_voltmer_960.jpg"
    },
    {
        "copyright": "Michael Karrer", "date": "2002-05-15", "explanation": "As Comet Ikeya-Zhang approached the Sun two months ago, it developed a complex blue ion tail.  The tail was composed of ions that boiled off the nucleus and were pushed away from the Sun by the out-flowing fast-moving particles of the solar wind.  Complexity in the tail is created by comet nucleus rotation, variability in the comet surface evaporation rate, and variability of the Sun's magnetic field and solar wind.  The above animation documents how Comet Ikeya-Zhang's tail changed over 30 minutes in ten consecutive 3-minute exposures on March 11.  Comet Ikeya Zhang is now fading as it heads back to the outer Solar System.  It should remain visible through a small telescope for another month.", "hdurl": "https://apod.nasa.gov/apod/image/0205/cometiz_karrer.gif", "media_type": "image", "service_version": "v1", "title": "Tail Wags of Comet Ikeya-Zhang", "url": "https://apod.nasa.gov/apod/image/0205/cometiz_karrer.gif"
    },
    {
        "copyright": "J\u00fcrgen Michelberger", "date": "2008-06-04", "explanation": "Bathed in sunlight, the International Space Station (ISS) arced through the evening sky above the town of Lauffen in southern Germany on May 31st. The timing of the bright passage was about 10 minutes after the launch of the Space Shuttle Discovery on the STS-124 mission from Kennedy Space Center, Florida, in the southeastern US.  Of course, Discovery was headed toward an orbital rendezvous with the ISS. In chasing after the space station, the shuttle also made a pass over Lauffen just 21 minutes after launch. With a camera fixed to a tripod, astronomer J\u00fcrgen Michelberger recorded both magnificent machines streaking overhead in two different time exposures, each about 2 minutes long, and merged them in this composite view. Parallax causes the paths of the ISS (right) and Discovery (near center) to seem to diverge as they were at very different altitudes. Stars (and bright planets) leave two, separated, short trails. The brief, flaring track of an Iridium satellite and faint dotted trail of a passing airplane are also visible. A close inspection will reveal a dim reddish track, the jettisoned external fuel tank, just left of Discovery. Placing your cursor over the picture should help identify some of the features.   digg_url = 'http://apod.nasa.gov/apod/ap080604.html'; digg_skin = 'compact';", "hdurl": "https://apod.nasa.gov/apod/image/0806/ISS_STS124_michelberger.jpg", "media_type": "image", "service_version": "v1", "title": "Chasing the ISS", "url": "https://apod.nasa.gov/apod/image/0806/ISS_STS124_michelberger_800.jpg"
    },
    {
        "date": "1998-12-25", "explanation": "If our Galaxy were a Christmas tree, planetary nebulae would adorn it like colorful lighted ornaments twinkling on a cosmic scale. Glowing shrouds of gas ejected by red giant stars, planetary nebulae like NGC 6578 (left) and IC 3568 last for a mere 10,000 years or so as swollen stellar giants are transformed into fading, cooling white dwarf stars. Meanwhile ... have a safe, happy holiday season and Best Wishes to all from APOD!", "hdurl": "https://apod.nasa.gov/apod/image/9812/ngc6578.jpg", "media_type": "image", "service_version": "v1", "title": "Nebulae For Christmas", "url": "https://apod.nasa.gov/apod/image/9812/ngc6578_1.jpg"
    },
    {
        "copyright": "Roberto\nColombari", "date": "2018-06-29", "explanation": "Unlike most entries in Charles Messier's famous catalog of deep sky objects, M24 is not a bright galaxy, star cluster, or nebula. It's a gap in nearby, obscuring interstellar dust clouds that allows a view of the distant stars in the Sagittarius spiral arm of our Milky Way galaxy. When you gaze at the star cloud with binoculars or small telescope you are looking through a window over 300 light-years wide at stars some 10,000 light-years or more from Earth. Sometimes called the Small Sagittarius Star Cloud, M24's luminous stars fill the left side of this gorgeous starscape. Covering about 4 degrees or the width of 8 full moons in the constellation Sagittarius, the telescopic field of view contains many small, dense clouds of dust and nebulae toward the center of the Milky Way, including reddish emission from IC 1284 near the top of the frame.", "hdurl": "https://apod.nasa.gov/apod/image/1806/M24Colombari.jpg", "media_type": "image", "service_version": "v1", "title": "Messier 24: Sagittarius Star Cloud", "url": "https://apod.nasa.gov/apod/image/1806/M24Colombari1024.jpg"
    }
]

export default dummyData